### ISSUE TITLE
Fix main container width on small devices

### ISSUE THREAD

**Issue by denissceluiko** [JustTsukihime/sejiens-datoriki#17]

**Comment by valdisAglonietisLU** [comment]
Changed width on small devices to 90%. Could change to 100%. Don't know.

**Comment by valdisAglonietisLU** [comment]
I merged it in already, because there were conflicts. So if 100%- then create SD-17-2 ?

**Comment by denissceluiko** [comment]
Es aizmirsu mark closed, jo es jau biju to salabojis 😅
